### ISSUE TITLE
issue 24

### ISSUE THREAD

**Issue by kimuraeiji214** [clthck/vmware_ma#3]
Hi, man. how is it going?

**Comment by clthck** [comment]
Hey yo, what's up?

**Comment by clthck** [comment]
http://swarts.gitlab.io/general/2016/09/22/my-favorite-online-course-platforms.html

**Comment by kimuraeiji214** [comment]
just wanted to know how you were doing

**Comment by clthck** [comment]
hey, u on slack? if not, plz check new msg there and follow the instruction. cheers
